blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/lukaisluka/poiera#readme
    about: Please check the documentation first
  - name: GitHub Discussions
    url: https://github.com/lukaisluka/poiera/discussions
    about: Use GitHub Discussions for questions that don't fit as issues
